### ISSUE TITLE
Support architecture specific base tuning profiles

### ISSUE THREAD

**Issue by niklas88** [openshift/cluster-node-tuning-operator#120]
Hi Everyone,
with Openshift now running on IBM Z a lot of effort is going into optimization and tuning. As part of this effort several very important tuning settings have been identified[0] which we would like to apply for all Openshift nodes running on Z. Some of these settings bring >5 *times* better network performance in some network streaming benchmarks and are thus very important for a good out of the box experience on our platform.
Similarly our colleagues working on IBM POWER also identified such architecture dependent base tuning settings and any  solution would therefore immediately benefit multiple platforms.

Now I did not find a native mechanism for architecture specific tuning in **tuned**  beyond the `virt_check` function to distinguish VMs from bare metal (Note that on IBM Z all OSs always run under at least one level of hardware virtualization).

So the best method I managed to come up with to have architecture dependent settings is to use additional profiles selected via `kubernetes.io/arch=s390` in combination with your **tuned** patch for "inheriting" from multiple profiles (though I couldn't test that with Openshift 4.2 so had to copy some settings). I think one advantage of this approach would be that even on future heterogeneous clusters admins would still have full control over each platform's tuning settings with a single.

`oc edit Tuned default -n openshift-cluster-node-tuning-operator`

With that in mind the base spec would look something like this:

```YAML
…
spec:
  profile:
…
# existing base profiles
…
  - data: |
      [main]
      summary=IBM Z Parent Tuning Profile
      include=openshift

      [sysctl]
      net.core.rmem_max=6291456
      net.core.wmem_max=4194304
      net.core.netdev_max_backlog=10000
      …

      [sysfs]
      /sys/class/net/queues/rx-0/rps_cpus=ff

      [net]
      features= tx on, rx on

      [vm]
      transparent_hugepages=never
    name: ibmz-openshift
  - data: |
      [main]
      summary=IBM Z Node Tuning Profile
      include=ibmz-openshift,openshift-node
    name: ibmz-openshift-node
  - data: |
      [main]
      summary=IBM Z Control Plane Tuning Profile
      include=bmz-opeshift,openshift-control-plane
  recommend:
…
  - match:
    - label: node-role.kubernetes.io/master
    - label: node-role.kubernetes.io/infra
    - label: kubernetes.io/arch
      value: s390x
    priority: 8
    profile: ibmz-openshift-control-plane
  - match:
    - label: kubernetes.io/arch
      value: s390x
    priority: 9
    profile: ibmz-openshift-node
status: {}
```
Before sending a patch for this I wanted to start a discussionand figure out if there might be a more elegant way and if this is something we could incorporate.

[0] As mentioned for example in this[ Red Hat Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1810124) (towards the end)

**Comment by jmencak** [comment]
Hello @niklas88 
Apologies for late response, I've completely missed this issue.  Is there a reason you cannot create custom profiles?  Please note that you're not supposed to edit the default profile as it will [get overwritten](https://docs.openshift.com/container-platform/4.2/nodes/nodes/nodes-node-tuning-operator.html).

**Comment by niklas88** [comment]
@jmencak the idea behind this feature request is to have an alternative set of defaults for a specific architecture such as IBM Z (aka s390x). The background for this is that our performance analysis team has identified a set of tuning parameters they think will make sense for basically all IBM Z systems running OpenShift. So we are basically looking for an architecture specific extension method for the default profile.

**Comment by jmencak** [comment]
@niklas88 understood and makes sense.  However, I believe any architecture-aware tuning should be part of the [tuned daemon](https://github.com/redhat-performance/tuned/) itself.  I'm told by tuned developers there is [tuned engine support](https://github.com/redhat-performance/tuned/pull/218) for that, however not in tuned 2.11 shipping in RHEL7.x.  Also, they do not have any architecture-specific profiles, so perhaps it is time to add them now.  For the time being I'm afraid it is custom profiles only.

/cc @zvonkok , @sjug , @yanirq for any additional thoughts.

**Comment by jmencak** [comment]
Not directly relevant to hardware architectures, but still close enough so linking: [cloud-provider specific support](https://bugzilla.redhat.com/show_bug.cgi?id=1787363) for tuned.

**Comment by niklas88** [comment]
@jmencak thank you for these pointers, this definitely sounds like alternatives worth looking into

**Comment by danijel-soldo** [comment]
@jmencak Hi, let me ping again since repeated measurements show some straight benefits when using some of the settings, so we are looking for a way to make it a part of the product. 

Just to clear things up, our only option is to write a custom profile just as you mentioned?
Our goal is to make it per default applyed on each OCP node running on a Z system.

**Comment by jmencak** [comment]
At the moment yes.  By contributing the tuned profile upstream all platforms, not just OCP is going to benefit.  If you need it "now", then custom profiles.
