### ISSUE TITLE
vanilla kubernetes compatibility

### ISSUE THREAD

**Issue by bcg62** [openshift/cluster-node-tuning-operator#198]
is there a way, or configuration in which this would run without openshift on vanilla kubernetes?

**Comment by jmencak** [comment]
You'd need to do quite a bit of changes for vanilla k8s.  Dependency on other operators like MCO for changing kernel boot parameters on RHCOS, removing things like updating ClusterOperator objects come to mind.  At this point it is very much tied to OpenShift.  You should be able to run this on OKD without issues.

**Comment by maxpain** [comment]
The same question.

**Comment by maxpain** [comment]
@bcg62 Have you managed to run this on a non-Openshift cluster?

**Comment by bcg62** [comment]
@maxpain quite some time ago I forked, modified, and rebuilt it to ignore/drop several of the openshift ecosystem objects it was looking for. It worked and ran on a non-openshift cluster but I would recommend using it this way. I only tested very minimal functionality.

**Comment by maxpain** [comment]
@bcg62 thank you for your response. What do you use instead of this?
