### ISSUE TITLE
Assign a priority class to pods

### ISSUE THREAD

**Issue by aveshagarwal** [openshift/cluster-node-tuning-operator#21]
Priority classes docs:
https://docs.openshift.com/container-platform/3.11/admin_guide/scheduling/priority_preemption.html#admin-guide-priority-preemption-priority-class

Example: https://github.com/openshift/cluster-monitoring-operator/search?q=priority&unscoped_q=priority

Notes: The pre-configured system priority classes (`system-node-critical` and `system-cluster-critical`) can only be assigned to pods in `kube-system` or `openshift-*` namespaces. Most likely, core operators and their pods should be assigned `system-cluster-critical`. Please do not assign `system-node-critical` (the highest priority) unless you are really sure about it.

**Comment by jmencak** [comment]
Thanks for this.  Currently considering a move under OLM.  Would the same apply for SLOs?

**Comment by jeremyeder** [comment]
Is this still required?

**Comment by aveshagarwal** [comment]
> Thanks for this. Currently considering a move under OLM. Would the same apply for SLOs?

In general, it would be useful to have a higher priority assigned to important pods so that they dont compete with normal users pods, but I am not sure what is the plan for operators under OLM. This issue was mostly for operators started by CVO.

**Comment by jmencak** [comment]
https://github.com/openshift/cluster-node-tuning-operator/pull/44
