### ISSUE TITLE
kernel parameters not being changed

### ISSUE THREAD

**Issue by NiallWard** [openshift/cluster-node-tuning-operator#358]
Hi

I think I'm missing something fundamental with this operator. I have created a custom kubelet yaml and the yaml for the configuration of the node tuning operator. The setting for  net.ipv4.ip_local_port_range is immediately applied to the openshift nodes, but none of the kernel parameters are. I can see by inspecting the tuned pod on the nodes that all the settings are picked up by tuned. I had thought that the attached custom-kubelet yaml would be sufficient to enable any non-whitelisted sysctl params, but apparently not. Would anyone be able to point out what I doing incorrectly or how to debug what is missing/wrong?
[custom_kubelet_CR.yaml.txt](https://github.com/openshift/cluster-node-tuning-operator/files/8605228/custom_kubelet_CR.yaml.txt)
[nodeTuningOperator.yaml.txt](https://github.com/openshift/cluster-node-tuning-operator/files/8605229/nodeTuningOperator.yaml.txt)

I'm currently on Openshift 4.9

**Comment by jmencak** [comment]
NTO does not process `KubeletConfig` in any way.  To set kernel parameters via NTO, you need to use MachineConfigPool matching described in the README.md.  An example of this is [here](https://github.com/openshift/cluster-node-tuning-operator/blob/master/examples/realtime-mc.yaml) and the associated [MCP](https://github.com/openshift/cluster-node-tuning-operator/blob/master/examples/realtime-mcp.yaml).

**Comment by NiallWard** [comment]
Thanks for the response. To be clear, the NTO is working on the correct nodes in some instances, I can set [sysctl] values in the yaml, apply them and see an instant response on the node, the sysctl value is changed immediately to match the one in the yaml. However, values like kernel.sem do not get changed. I was using kubeletconfig in an effort to allow sysctls on the node that might be considered unsafe, but to no avail. Any ideas what could be blocking me ? I would have thought changing kernel.sem would be a common use case, so I suspect I'm doing something wrong, or missing something basic.

**Comment by NiallWard** [comment]
On an associated note, is there any doc regarding the distinction between the NTO and the Machine Config operator? They would appear on face value to do the same thing

**Comment by jmencak** [comment]
> On an associated note, is there any doc regarding the distinction between the NTO and the Machine Config operator? They would appear on face value to do the same thing

Yes, there are docs but scattered across OpenShift docs, RHEL docs (for `TuneD`).  Basically, NTO ships a set of well-established and used profiles, does a rollback of changes without reboot (unless using bootloader plug-in) unlike MCO and has some specific advantages like setting C-states that MCO cannot do.  Others to note automatic calculation of CPU-masks for irqbalance, tuning network cards...  Just go over the `TuneD` docs.  I've also provided TuneD plug-in documentation upstrem that will hopefully soon merge.

As for you ability to set kernel parameters, it is documented both upstream (here) and downstream (OCP docs) and I already even pointed you out to an example.  Hope that at least the example helps.  Note you have to target a machine config pool to be able to use the bootloader plug-in (hence "not fully supported" as written in the README.md).  NTO will use MCO to set kernel parameters. Thank you.
