### ISSUE TITLE
Ubuntu 22.04 with containerd

### ISSUE THREAD

**Issue by maxpain** [openshift/cluster-node-tuning-operator#379]
Hello. Is it possible to use this operator in a cluster, deployed via `Kubespray` using `Ubuntu 22.04` instead of `RHCOS` and `containerd` instead of `cri-o`?
Or it is only for Openshift?

**Comment by jmencak** [comment]
Hello, thank you for your interest.  The short answer is that we haven't tried and are not planning to add support for this.  Yes, it is primarily intended for OpenShift.

**Comment by maxpain** [comment]
Thanks!
