### ISSUE TITLE
No PerformanceProfile in ClusterOperator relatedObjects

### ISSUE THREAD

**Issue by nekop** [openshift/cluster-node-tuning-operator#534]
Since PerformanceProfile is merged into this project, it needs to be listed as a relatedObjects. For example, must-gather tool gets resources using this field and currently PerformanceProfile is not collected by the standard cluster operator must-gather.

**Comment by jmencak** [comment]
Thank you for the report.  Apologies, I missed it.  Feel free to file a Jira issue next time, those do not get overlooked.

Fixed by: https://github.com/openshift/cluster-node-tuning-operator/pull/655
/close
